### ISSUE TITLE
[Question / Suggestion] Is it possible to make your firmware skip booting

### ISSUE THREAD

**Issue by 1n5aN1aC** [strijar/x6100_gui#2]
Greetings,
I love your firmware, and find it better in a lot of ways.

However, I still wish to use CAT control sometimes.  I respect your decision to not implement this, which is why I am interested instead in a feature where I could hold a button when turning on the radio to cause your firmware to skip booting, allow the internal flash to boot instead.

I've seen this in a different firmware for the X6100, I think it was Armbian.  Maybe this could be a way to satisfy those of us who are sometimes interested in CAT control, without having to implement it yourself.

Either way, thanks for all your hard work!

**Comment by strijar** [comment]
Yes, I saw the boot selection. But in my case it is enough to pull out the SD card. The choice of an alternative boot is justified when the firmware (or firmwares) is in the internal memory.

**Comment by 1n5aN1aC** [comment]
This feature request has not been fulfilled, but I no longer have a need for it, so I am closing this feature request.
