### ISSUE TITLE
Feature request: change power/ meter color?

### ISSUE THREAD

**Issue by d3m3vilurr** [strijar/x6100_gui#3]
A default glay color is good indoors, but when I operate x6100 outdoors, I couldn't see the gauge bar.
can you add the color change option to the setting?

**Comment by strijar** [comment]
I have answered similar questions many times. Until a professional designer joins the project, I will not change anything in the GUI.

**Comment by d3m3vilurr** [comment]
oh I see.

another thing, can I know how to compile this project & build image?

**Comment by strijar** [comment]
You need to be able to work with buildroot. Build the system with it, and then build this application. If there is no such experience, then it will not be easy.

**Comment by d3m3vilurr** [comment]
can you share `.config` file for the buildroot?

**Comment by strijar** [comment]
Everything has been available for a long time. Who needed it - already found and builded

**Comment by d3m3vilurr** [comment]
Yep. I found config from a branch of your fork repo. Thank you 👍
